// AUTO-GENERATED BY scripts/generate-allowlists.mjs - DO NOT EDIT DIRECTLY
use lazy_static::lazy_static;
use std::collections::{HashSet, HashMap};

lazy_static! {
    pub static ref COMPONENT_PROP_ALLOWLIST: HashMap<&'static str, HashMap<&'static str, HashSet<&'static str>>> = {
        let mut map: HashMap<&'static str, HashMap<&'static str, HashSet<&'static str>>> = HashMap::new();
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("primary");
                set.insert("secondary");
                set.insert("error");
                set.insert("warning");
                set.insert("success");
                set.insert("destructive");
                set.insert("info");
                set.insert("beta");
                set.insert("outline");
                set.insert("red");
                set.insert("green");
                set.insert("neutral");
                set.insert("orange");
                set.insert("purple");
                set.insert("teal");
                set.insert("teal-subtle");
                set.insert("blue");
                comp_map.insert("variant", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("filled");
                set.insert("dot");
                comp_map.insert("appearance", set);
            }
            map.insert("Badge", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("default");
                set.insert("alert");
                set.insert("error");
                set.insert("secondary");
                comp_map.insert("variant", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("base");
                set.insert("sm");
                comp_map.insert("size", set);
            }
            map.insert("Banner", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("sm");
                set.insert("base");
                comp_map.insert("size", set);
            }
            map.insert("Breadcrumbs", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("base");
                set.insert("square");
                set.insert("circle");
                comp_map.insert("shape", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("xs");
                set.insert("sm");
                set.insert("base");
                set.insert("lg");
                comp_map.insert("size", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("primary");
                set.insert("secondary");
                set.insert("ghost");
                set.insert("destructive");
                set.insert("secondary-destructive");
                set.insert("outline");
                comp_map.insert("variant", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("submit");
                set.insert("reset");
                set.insert("button");
                comp_map.insert("type", set);
            }
            map.insert("Button", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("default");
                set.insert("error");
                comp_map.insert("variant", set);
            }
            map.insert("Checkbox", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("sm");
                set.insert("base");
                set.insert("lg");
                comp_map.insert("size", set);
            }
            map.insert("ClipboardText", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("none");
                set.insert("sum");
                comp_map.insert("accumulate", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("replace");
                set.insert("sum");
                comp_map.insert("additive", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("auto");
                set.insert("baseline");
                set.insert("before-edge");
                set.insert("text-before-edge");
                set.insert("middle");
                set.insert("central");
                set.insert("after-edge");
                set.insert("text-after-edge");
                set.insert("ideographic");
                set.insert("alphabetic");
                set.insert("hanging");
                set.insert("mathematical");
                set.insert("inherit");
                comp_map.insert("alignmentBaseline", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("no");
                set.insert("yes");
                comp_map.insert("allowReorder", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("initial");
                set.insert("medial");
                set.insert("terminal");
                set.insert("isolated");
                comp_map.insert("arabicForm", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("auto");
                set.insert("sRGB");
                set.insert("linearRGB");
                set.insert("inherit");
                comp_map.insert("colorInterpolationFilters", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("auto");
                set.insert("use-script");
                set.insert("no-change");
                set.insert("reset-size");
                set.insert("ideographic");
                set.insert("alphabetic");
                set.insert("hanging");
                set.insert("mathematical");
                set.insert("central");
                set.insert("middle");
                set.insert("text-after-edge");
                set.insert("text-before-edge");
                set.insert("inherit");
                comp_map.insert("dominantBaseline", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("nonzero");
                set.insert("evenodd");
                set.insert("inherit");
                comp_map.insert("fillRule", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("butt");
                set.insert("round");
                set.insert("square");
                set.insert("inherit");
                comp_map.insert("strokeLinecap", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("miter");
                set.insert("round");
                set.insert("bevel");
                set.insert("inherit");
                comp_map.insert("strokeLinejoin", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("start");
                set.insert("middle");
                set.insert("end");
                set.insert("inherit");
                comp_map.insert("textAnchor", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("glyph");
                set.insert("full");
                comp_map.insert("variant", set);
            }
            map.insert("CloudflareLogo", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("ts");
                set.insert("tsx");
                set.insert("jsonc");
                set.insert("bash");
                set.insert("css");
                comp_map.insert("lang", set);
            }
            map.insert("Code", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("xs");
                set.insert("sm");
                set.insert("base");
                set.insert("lg");
                comp_map.insert("size", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("right");
                set.insert("top");
                comp_map.insert("inputSide", set);
            }
            map.insert("Combobox", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("sm");
                set.insert("base");
                set.insert("lg");
                comp_map.insert("size", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("default");
                set.insert("subtle");
                comp_map.insert("variant", set);
            }
            map.insert("DateRangePicker", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("base");
                set.insert("sm");
                set.insert("lg");
                set.insert("xl");
                comp_map.insert("size", set);
            }
            map.insert("Dialog", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("default");
                set.insert("danger");
                comp_map.insert("variant", set);
            }
            map.insert("DropdownMenu", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("sm");
                set.insert("base");
                set.insert("lg");
                comp_map.insert("size", set);
            }
            map.insert("Empty", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("none");
                set.insert("sm");
                set.insert("base");
                set.insert("lg");
                comp_map.insert("gap", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("2up");
                set.insert("side-by-side");
                set.insert("2-1");
                set.insert("1-2");
                set.insert("1-3up");
                set.insert("3up");
                set.insert("4up");
                set.insert("6up");
                set.insert("1-2-4up");
                comp_map.insert("variant", set);
            }
            map.insert("Grid", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("xs");
                set.insert("sm");
                set.insert("base");
                set.insert("lg");
                comp_map.insert("size", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("default");
                set.insert("error");
                comp_map.insert("variant", set);
            }
            map.insert("Input", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("xs");
                set.insert("sm");
                set.insert("base");
                set.insert("lg");
                comp_map.insert("size", set);
            }
            map.insert("InputGroup", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("inline");
                set.insert("current");
                set.insert("plain");
                comp_map.insert("variant", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("no-referrer");
                set.insert("no-referrer-when-downgrade");
                set.insert("origin");
                set.insert("origin-when-cross-origin");
                set.insert("same-origin");
                set.insert("strict-origin");
                set.insert("strict-origin-when-cross-origin");
                set.insert("unsafe-url");
                comp_map.insert("referrerPolicy", set);
            }
            map.insert("Link", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("sm");
                set.insert("base");
                set.insert("lg");
                comp_map.insert("size", set);
            }
            map.insert("Loader", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("full");
                set.insert("simple");
                comp_map.insert("controls", set);
            }
            map.insert("Pagination", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("top");
                set.insert("bottom");
                set.insert("left");
                set.insert("right");
                comp_map.insert("side", set);
            }
            map.insert("Popover", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("default");
                set.insert("error");
                comp_map.insert("variant", set);
            }
            map.insert("Radio", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("xs");
                set.insert("sm");
                set.insert("base");
                set.insert("lg");
                comp_map.insert("size", set);
            }
            map.insert("Select", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("xs");
                set.insert("sm");
                set.insert("base");
                set.insert("lg");
                comp_map.insert("size", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("default");
                set.insert("error");
                comp_map.insert("variant", set);
            }
            map.insert("SensitiveInput", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("sidebar");
                set.insert("floating");
                set.insert("inset");
                comp_map.insert("variant", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("left");
                set.insert("right");
                comp_map.insert("side", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("icon");
                set.insert("offcanvas");
                set.insert("none");
                comp_map.insert("collapsible", set);
            }
            map.insert("Sidebar", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("default");
                set.insert("neutral");
                comp_map.insert("variant", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("sm");
                set.insert("base");
                set.insert("lg");
                comp_map.insert("size", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("submit");
                set.insert("reset");
                set.insert("button");
                comp_map.insert("type", set);
            }
            map.insert("Switch", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("auto");
                set.insert("fixed");
                comp_map.insert("layout", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("default");
                set.insert("selected");
                comp_map.insert("variant", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("left");
                set.insert("right");
                comp_map.insert("sticky", set);
            }
            map.insert("Table", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("segmented");
                set.insert("underline");
                comp_map.insert("variant", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("base");
                set.insert("sm");
                comp_map.insert("size", set);
            }
            map.insert("Tabs", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("heading1");
                set.insert("heading2");
                set.insert("heading3");
                set.insert("body");
                set.insert("secondary");
                set.insert("success");
                set.insert("error");
                set.insert("mono");
                set.insert("mono-secondary");
                comp_map.insert("variant", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("xs");
                set.insert("sm");
                set.insert("base");
                set.insert("lg");
                comp_map.insert("size", set);
            }
            {
                let mut set = HashSet::new();
                set.insert("h1");
                set.insert("h2");
                set.insert("h3");
                set.insert("h4");
                set.insert("h5");
                set.insert("h6");
                set.insert("p");
                set.insert("span");
                set.insert("label");
                set.insert("dt");
                set.insert("dd");
                set.insert("li");
                set.insert("figcaption");
                set.insert("legend");
                set.insert("pre");
                set.insert("code");
                set.insert("em");
                set.insert("strong");
                set.insert("small");
                set.insert("abbr");
                set.insert("time");
                comp_map.insert("as", set);
            }
            map.insert("Text", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("default");
                set.insert("success");
                set.insert("error");
                set.insert("warning");
                set.insert("info");
                comp_map.insert("variant", set);
            }
            map.insert("Toasty", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("xs");
                set.insert("sm");
                set.insert("base");
                set.insert("lg");
                comp_map.insert("size", set);
            }
            map.insert("Toolbar", comp_map);
        }
        {
            let mut comp_map = HashMap::new();
            {
                let mut set = HashSet::new();
                set.insert("top");
                set.insert("bottom");
                set.insert("left");
                set.insert("right");
                comp_map.insert("side", set);
            }
            map.insert("Tooltip", comp_map);
        }
        map
    };
}

pub fn get_valid_prop_values(component: &str, prop: &str) -> Option<&'static HashSet<&'static str>> {
    COMPONENT_PROP_ALLOWLIST.get(component).and_then(|props| props.get(prop))
}
